# Workflow para deploy de conteúdo estático com build
name: Deploy static content to Pages

on:
  # Executa o workflow ao fazer push para a branch principal
  push:
    branches: ["main"]

  # Permite executar o workflow manualmente a partir da aba Actions
  workflow_dispatch:

# Define permissões do GITHUB_TOKEN para permitir deploy para GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deploy simultâneo
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # ou a versão Node do seu projeto

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Publica a pasta dist, que contém o build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
